name: "Setup test environment"
description: "Setup docker container with test environment."
inputs:
  cmd:
    description: "Command to execute inside docker container."
    required: true
    default: "pytest"
runs:
  using: "docker"
  image: "../../../testing/Dockerfile"
  args:
    - ${{ inputs.cmd }}