name: Run tests

on:
  push:
    branches-ignore:
      - '!master'
env:
  FOOBAR: hello

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run tests
        run: FOOBAR=$FOOBAR docker-compose -f "testing/docker-compose.yml" up --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "testing/docker-compose.yml" down
