name: Run tests

on:
  push:
    branches-ignore:
      - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run tests
        uses: ./.github/actions/qa
        with:
#          cmd: pytest test_example.py::test_allure_simple_test -vv -s
          cmd: find . | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
        env:
          TESTS_PKG: testing
