name: Run tests

on:
  push:
    branches-ignore:
      - '!master'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
